[package]
name = "bgu"
edition = "2021"
version = "0.1.0"
license = "Apache-2.0"
repository = "https://github.com/i18n-site/bin.git"
homepage = "https://github.com/i18n-site/bin/tree/main/bgu"
description = "bgu"

[dependencies]
