[target.aarch64-apple-darwin]
image = "i18nsite/aarch64-apple-darwin-cross:latest"

[target.x86_64-apple-darwin]
image = "i18nsite/x86_64-apple-darwin-cross:latest"

[target.aarch64-pc-windows-msvc]
image = "i18nsite/aarch64-pc-windows-msvc-cross:latest"
