name: build
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  build:
    name: build
    strategy:
      matrix:
        platform: [macos-latest,ubuntu-latest,mac-arm,windows-latest]
           # [self-hosted, linux, ARM64]
        # python-version: [3.9]
        # platform: [windows-latest]
        # platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    # https://docs.github.com/zh/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures
    steps:
      - if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      # - uses: GuillaumeFalourd/setup-rsync@v1.2
      - uses: AnimMouse/setup-rclone@v1
      - uses: actions/checkout@v4
        with:
          lfs: true
      - if: runner.os == 'linux'
        uses: goto-bus-stop/setup-zig@v2
        # with:
        #   version: 0.11.0
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: nightly
            override: true
            # components: rustfmt, clippy

      - name: prepare
        shell: bash
        env:
          ENC_PASSWD: ${{ secrets.ENC_PASSWD }}
        run: |
          ./sh/dist/os.sh

      - name: build
        shell: bash
        run: |
          ./sh/cross.sh

      - name: dist
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./sh/dist/bin.sh

      # - name: cancel_if_failure
      #   if: failure()
      #   uses: andymckay/cancel-action@0.4

  ver:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: AnimMouse/setup-rclone@v1
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: ver
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          ENC_PASSWD: ${{ secrets.ENC_PASSWD }}
        run: |
          cd sh/dist
          ./os.sh
          ./dist.sh

